### Auth routes

### REGISTER
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
		"username": "bob_sled",
		"email": "bobbies@email.com",
		"password": "bobselitepassword"
	}

### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
	"username": "bob_sled",
	"password": "bobselitepassword"
}